name: Github Actions - Cron Job
run-name: Running - ${{ github.event_name }}

on:
  schedule:
    - cron: '42 02 * * *'  # 23:42 BRT

jobs:
  on-workflow-dispatch:
    name: On Workflow Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Executando
        run: |
          echo "Hello, World"