<<<<<<< HEAD
name: Github Actions - Trigger 1
run-name: Running - Trigger 1
on: [push, workflow_dispatch]
=======
name: Github Actions - Cron Job
run-name: Running - ${{ github.event_name }}

on:
  schedule:
    - cron: '45 2 * * *'  

>>>>>>> ed317c22837b22421042b5ba2f2b1a376bb4b3fc
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
<<<<<<< HEAD
          echo "Este é o workflow de Trigger 1"
=======
          echo "Hello, World"
>>>>>>> ed317c22837b22421042b5ba2f2b1a376bb4b3fc
