name: Github Actions - Cron Job
run-name: Running - ${{ github.event_name }}

on:
  schedule:
    - cron: '59 2 4 11 *'  # 23:59 BRT do dia 03/11/2025;

jobs:
  on-workflow-dispatch:
    name: On Workflow Dispatch
    runs-on: ubuntu-latest
    steps:
      - name: Executando
        run: |
          echo "Hello, World"