name: Github Actions - Teste com dependência
run-name: Running - Teste com dependência
on:
  push:
    workflow_dispatch:

jobs:
  test_unit:
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: echo "Este é o job de setup."

  test_api:
    needs: test_unit
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: echo "Este é o job de teste de API."

  test_ui:
    needs: [test_unit, test_api]
    runs-on: ubuntu-20.04
    steps:
      - name: Comentário
        run: echo "Este é o job de teste de UI."