name: Github Actions - Configuração de variável de repositório
run-name: Configurando variável de repositório
on:
  push:
    branches:
      - main
env:
  test_env: "Variável de ambiente do repositório"
  var1:  ${{ secrets.test_secret }}
  var2:  ${{ vars.test_var }}
jobs:
  on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Comentário
        run: |
          echo "Esta é uma variável de ambiente do repositório: $test_env"
          echo "Esta é uma variável secreta do repositório: ${var1}"
          echo "Esta é uma variável do repositório: ${var2}"