name: Github Actions - Matrix Strategy
run-name: Matrix Strategy
on: [push, workflow_dispatch]

jobs:
  matrix_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        navegador: [chrome, firefox, edge]
        tag: [tag_1, tag_2, tag_3]
        framework: [react, angular, vue]
      fail-fast: false
    steps:
      - name: Coment√°rio inicial
        run: echo ${{ matrix.navegador }}